repos:
-   repo: local
    hooks:
    -   id: prevent-master
        name: Prevent master
        entry: poetry run poe prevent-master
        pass_filenames: false
        language: system
        stages:
            - commit
            - push
    -   id: lint
        name: Lint
        entry: poetry run poe lint
        pass_filenames: false
        language: system
        stages:
            - commit
            - push
    -   id: format
        name: Autoformatter
        entry: poetry run poe format
        pass_filenames: false
        language: system
        stages:
            - commit
            - push
    -   id: test
        name: Test
        entry: poetry run poe test
        pass_filenames: false
        language: system
        stages:
            - push
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.24.0
    hooks:
    -   id: commitizen
        stages:
            - commit-msg